# Generated by Django 6.1.1 on 2026-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('Number_plate', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Mobile_no', models.IntegerField()),
                ('Address', models.TextField()),
                ('Date', models.DateField()),
                ('Day', models.CharField(max_length=15)),
            ],
        ),
    ]
